export const DEFAULT_BACKGROUND_COLOR = "#888787";
export const DEFAULT_BACKGROUND_COLOR_HEADER = "#2D0097";
export const DEFAULT_TEXT_COLOR = "#010CE3";
export const DEFAULT_COLOR = "#010CE3";
export const SECOND_BACKGROUND_COLOR = "#CDD0D5";